# Old code that Stephen Grider uses in video
# FROM node:16-alpine

# WORKDIR '/app'

# COPY package.json .

# RUN npm install

# COPY . .

# CMD ["npm", "run", "start"]


# New code from Q&A because otherwise the right user permissions aren't given to user inside the container

FROM node:16-alpine
 
USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app
 
COPY --chown=node:node ./package.json ./

RUN npm install

# Potentially we could remove this line below
COPY --chown=node:node ./ ./
 
CMD ["npm", "start"]